# Jekyll configuration

name: CSE Readiness Repo
description: An Index of docs, videos, and more for readiness and upskilling

# url is currently only used only for the RSS feed in feed.xml
url: https://tarockey.github.io/

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: tarockey.github.io

# This can be '' to hide the Github nav button
github: 'tarockey/tarockey.github.io'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# The 'comments' setting enables comments. You'll need to select either
# disqus or isso below to choose a comment system. Individual posts can
# override 'comments' to disable on a post-by-post basis.
comments: true

# Set this to your public isso URL to enable comments via isso. Set to '' to disable isso.
isso: ''

# Set this to your disqus shortname to enable comments via disqus. Set to '' to disable disqus.
disqus: ''

collections:
  resources:
    output: true
    permalink: /:path


permalink: /:categories/:title
paginate: 3

highlighter: rouge
markdown: kramdown
plugins: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE']